/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pemrograman_berbasis_dekstop.view;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import pemrograman_berbasis_dekstop.DBConnection;
import pemrograman_berbasis_dekstop.entity.Pelanggan;
import pemrograman_berbasis_dekstop.model.PelangganModel;

/**
 *
 * @author user
 */
public class FormPelanggan extends javax.swing.JDialog {

    /**
     * Creates new form FormPelanggan
     */
    private Connection connection;
    private Pelanggan Pelanggan;
    private PelangganModel PelangganModel;
    private FormDataPelanggan FormDataPelanggan;
    
    public FormPelanggan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        connection = DBConnection.newgetInstant();
        Pelanggan = new Pelanggan();
        PelangganModel = new PelangganModel(connection);
        FormDataPelanggan = new FormDataPelanggan(parent, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonBaru = new javax.swing.JButton();
        buttonTambah = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonData = new javax.swing.JButton();
        textKode = new javax.swing.JTextField();
        textNama = new javax.swing.JTextField();
        textSatuan = new javax.swing.JTextField();
        textHargaSatuan = new javax.swing.JFormattedTextField();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        buttonBaru1 = new javax.swing.JButton();
        buttonTambah1 = new javax.swing.JButton();
        buttonUbah1 = new javax.swing.JButton();
        buttonHapus1 = new javax.swing.JButton();
        buttonData1 = new javax.swing.JButton();
        textKode1 = new javax.swing.JTextField();
        textNama1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAlamat = new javax.swing.JTextArea();
        textTelepon = new javax.swing.JTextField();

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Kode");

        jLabel2.setText("Nama");

        jLabel3.setText("Satuan");

        jLabel4.setText("Harga Satuan");

        buttonBaru.setText("Baru");
        buttonBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBaruActionPerformed(evt);
            }
        });

        buttonTambah.setText("Tambah");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        buttonUbah.setText("Ubah");
        buttonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahActionPerformed(evt);
            }
        });

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonData.setText("Data");
        buttonData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(buttonBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonTambah)
                        .addGap(18, 18, 18)
                        .addComponent(buttonUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(buttonHapus)
                        .addGap(18, 18, 18)
                        .addComponent(buttonData))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textKode)
                            .addComponent(textNama)
                            .addComponent(textSatuan)
                            .addComponent(textHargaSatuan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textHargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBaru)
                    .addComponent(buttonTambah)
                    .addComponent(buttonUbah)
                    .addComponent(buttonHapus)
                    .addComponent(buttonData))
                .addGap(39, 39, 39))
        );

        jButton6.setText("jButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("Kode");

        jLabel6.setText("Nama");

        jLabel7.setText("Alamat");

        jLabel8.setText("Telepon");

        buttonBaru1.setText("BARU");
        buttonBaru1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBaru1ActionPerformed(evt);
            }
        });

        buttonTambah1.setText("TAMBAH");
        buttonTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambah1ActionPerformed(evt);
            }
        });

        buttonUbah1.setText("UBAH");
        buttonUbah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbah1ActionPerformed(evt);
            }
        });

        buttonHapus1.setText("HAPUS");
        buttonHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapus1ActionPerformed(evt);
            }
        });

        buttonData1.setText("DATA");
        buttonData1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonData1ActionPerformed(evt);
            }
        });

        textAlamat.setColumns(20);
        textAlamat.setRows(5);
        jScrollPane1.setViewportView(textAlamat);

        textTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTeleponActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                            .addComponent(textNama1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textKode1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textTelepon)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonBaru1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(buttonTambah1)
                        .addGap(34, 34, 34)
                        .addComponent(buttonUbah1)
                        .addGap(27, 27, 27)
                        .addComponent(buttonHapus1)
                        .addGap(26, 26, 26)
                        .addComponent(buttonData1)))
                .addGap(0, 72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textKode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(textTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBaru1)
                    .addComponent(buttonTambah1)
                    .addComponent(buttonUbah1)
                    .addComponent(buttonHapus1)
                    .addComponent(buttonData1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBaruActionPerformed
        // TODO add your handling code here:
        textKode1.setText(null);
        textNama1.setText(null);
        textAlamat.setText(null);
        textTelepon.setText(null);
        textKode1.requestFocus();
    }//GEN-LAST:event_buttonBaruActionPerformed

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:
        Pelanggan.setKode(textKode1.getText());
        Pelanggan.setNama(textNama1.getText());
        Pelanggan.setAlamat(textAlamat.getText());
        Pelanggan.setTelepon(textTelepon.getText());
        
        try{
            connection.setAutoCommit(false);
            PelangganModel.insert(Pelanggan);
            connection.commit();
            JOptionPane.showMessageDialog(this, "Data berhasil ditambah","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(this, "Data Gagal Ditambah","KESALAHAN", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
     
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed
        // TODO add your handling code here:
        Pelanggan.setKode(textKode1.getText());
        Pelanggan.setNama(textNama1.getText());
        Pelanggan.setAlamat(textAlamat.getText());
        Pelanggan.setTelepon(textTelepon.getText());
        
        try{
            connection.setAutoCommit(false);
            PelangganModel.update(Pelanggan);
            connection.commit();
            JOptionPane.showMessageDialog(this, "Data berhasil diubah","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(this, "Data Gagal Diubah","KESALAHAN", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

    }//GEN-LAST:event_buttonUbahActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        Pelanggan.setKode(textKode1.getText());
        Pelanggan.setNama(textNama1.getText());
        Pelanggan.setAlamat(textAlamat.getText());
        Pelanggan.setTelepon(textTelepon.getText());
        
        try{
            connection.setAutoCommit(false);
            PelangganModel.delete(Pelanggan);
            connection.commit();
            JOptionPane.showMessageDialog(this, "Data berhasil diHAPUS","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(this, "Data Gagal DiHAPUS","KESALAHAN", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDataActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_buttonDataActionPerformed

    private void buttonBaru1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBaru1ActionPerformed
        // TODO add your handling code here:
        textKode1.setText(null);
        textNama1.setText(null);
        textAlamat.setText(null);
        textTelepon.setText(null);
        textKode1.requestFocus();
       
    }//GEN-LAST:event_buttonBaru1ActionPerformed

    private void textTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTeleponActionPerformed

    private void buttonTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambah1ActionPerformed
        // TODO add your handling code here:
        Pelanggan.setKode(textKode1.getText());
        Pelanggan.setNama(textNama1.getText());
        Pelanggan.setAlamat(textAlamat.getText());
        Pelanggan.setTelepon(textTelepon.getText());
        
        try{
            connection.setAutoCommit(false);
            PelangganModel.insert(Pelanggan);
            connection.commit();
            JOptionPane.showMessageDialog(this, "Data berhasil ditambah","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(this, "Data Gagal Ditambah","KESALAHAN", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_buttonTambah1ActionPerformed

    private void buttonUbah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbah1ActionPerformed
        // TODO add your handling code here:
         Pelanggan.setKode(textKode1.getText());
        Pelanggan.setNama(textNama1.getText());
        Pelanggan.setAlamat(textAlamat.getText());
        Pelanggan.setTelepon(textTelepon.getText());
        
        try{
            connection.setAutoCommit(false);
            PelangganModel.update(Pelanggan);
            connection.commit();
            JOptionPane.showMessageDialog(this, "Data berhasil diubah","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(this, "Data Gagal Diubah","KESALAHAN", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_buttonUbah1ActionPerformed

    private void buttonHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapus1ActionPerformed
        // TODO add your handling code here:
         Pelanggan.setKode(textKode1.getText());
        Pelanggan.setNama(textNama1.getText());
        Pelanggan.setAlamat(textAlamat.getText());
        Pelanggan.setTelepon(textTelepon.getText());
        
        try{
            connection.setAutoCommit(false);
            PelangganModel.delete(Pelanggan);
            connection.commit();
            JOptionPane.showMessageDialog(this, "Data berhasil diHAPUS","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(this, "Data Gagal DiHAPUS","KESALAHAN", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_buttonHapus1ActionPerformed

    private void buttonData1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonData1ActionPerformed
        // TODO add your handling code here:
        FormDataPelanggan.show();
        Pelanggan = FormDataPelanggan.getSelectionRow1();
        if (Pelanggan != null){
            textKode1.setText(Pelanggan.getKode());
            textNama1.setText(Pelanggan.getNama());
            textAlamat.setText(Pelanggan.getAlamat());
            textTelepon.setText(Pelanggan.getTelepon());
        }
        dispose();
    }//GEN-LAST:event_buttonData1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormPelanggan dialog = new FormPelanggan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBaru;
    private javax.swing.JButton buttonBaru1;
    private javax.swing.JButton buttonData;
    private javax.swing.JButton buttonData1;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonHapus1;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JButton buttonTambah1;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JButton buttonUbah1;
    private javax.swing.JButton jButton6;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAlamat;
    private javax.swing.JFormattedTextField textHargaSatuan;
    private javax.swing.JTextField textKode;
    private javax.swing.JTextField textKode1;
    private javax.swing.JTextField textNama;
    private javax.swing.JTextField textNama1;
    private javax.swing.JTextField textSatuan;
    private javax.swing.JTextField textTelepon;
    // End of variables declaration//GEN-END:variables
}
